Repository Sowith/sowith, pull requests merged in 2023-12, with the labels that each got.

#54 🛠Feat: 게시물 작성 - 데이터 연동 && Atom 추가 #53
  src/assets/icon/icon-image-upload.svg
  src/components/common/CheckBox.tsx
  src/components/common/FolderList.tsx
  src/components/main/MainPostItem.tsx
  src/components/post/PostFilterPreview.tsx
  src/components/post/PostHeader.tsx
  src/components/post/PostInput.tsx
  src/components/post/PostSearchBar.tsx
  src/components/post/PostSelectedFilter.tsx
  src/components/post/PostSelectedPicture.tsx
  src/components/post/PostUserItem.tsx
  src/hooks/useImageUpload.tsx
  src/hooks/useModalControl.tsx
  src/hooks/useformatRelativeTime.tsx
  src/pages/PostTS.tsx
  src/pages/post/PostCreateFolderPage.tsx
  src/pages/post/PostFilterPage.tsx
  src/pages/post/PostInputInfoPage.tsx
  src/pages/post/PostSelectFolderPage.tsx
  src/pages/post/PostSelectHashTagPage.tsx
  src/pages/post/PostSelectLocationPage.tsx
  src/pages/post/PostSelectUserTagPage.tsx
  src/recoil/postFormState.ts
Labels: enhancement, style, refactor

#55 🎨Design: 게시글 뷰 디자인 구현 #43 Revert
  src/components/main/MainComment.tsx
  src/components/main/MainUserItem.tsx
  src/hooks/useImageUpload.tsx
  src/pages/main/MainPostViewPage.tsx
Labels: enhancement, style

#58 ♻️Refactor: 그룹 기능 임시 제거 #57
  .prettierrc
  src/App.tsx
  src/components/common/GroupUI.tsx
  src/components/common/StepBar.tsx
  src/components/profile/ProfileTapMenu.tsx
  src/components/profile/profileBottom/profileBottomGroup.tsx
  src/components/search/SearchAccountItem.tsx
  src/components/search/SearchAccountList.tsx
  src/components/search/SearchBar.tsx
  src/components/search/SearchFolderItem.tsx
  src/components/search/SearchFolderList.tsx
  src/components/search/SearchGroupList.tsx
  src/components/search/SearchHistoryItem.tsx
  src/components/search/SearchPostItem.tsx
  src/components/search/SearchPostList.tsx
  src/components/search/SearchTagItem.tsx
  src/components/search/SearchTagList.tsx
  src/components/search/SearchTrendingFolderItem.tsx
  src/components/search/SearchTrendingFolderList.tsx
  src/components/search/SearchTrendingTagItem.tsx
  src/components/search/SearchTrendingTagList.tsx
  src/hooks/useCreateKeywords.ts
  src/pages/profile/ProfileGroupDetailPage.tsx
  src/pages/search/SearchByCategoryPage.tsx
  src/pages/search/SearchHistoryPage.tsx
  src/pages/search/SearchMainPage.tsx
  src/pages/search/SearchTrendingFolderPage.tsx
  src/pages/search/SearchTrendingGroupPage.tsx
Labels: enhancement, style, refactor

#59 🛠Feat: 검색 기능 구현 #22
  package-lock.json
  src/components/search/SearchHistoryItem.tsx
  src/hooks/useDeleteSearchHistory.ts
  src/hooks/useFirestoreCreate.tsx
  src/hooks/useFirestoreDelete.tsx
  src/hooks/useSignUp.ts
  src/pages/search/SearchHistoryPage.tsx
Labels: bug, enhancement, refactor

#61 🛠Feat: 게시물 작성 - 데이터 연동 && Atom 추가 #53 Revert
  src/assets/icon/icon-create-folder.svg
  src/components/common/FolderList.tsx
  src/components/post/PostHeader.tsx
  src/components/post/PostInput.tsx
  src/components/post/PostSearchBar.tsx
  src/components/post/PostUserItem.tsx
  src/firebase/config.js
  src/hooks/useCreateKeywords.ts
  src/hooks/useFirestoreCreate.tsx
  src/hooks/useSignUp.ts
  src/pages/post/PostInputInfoPage.tsx
  src/pages/post/PostSelectFolderPage.tsx
  src/pages/post/PostSelectHashTagPage.tsx
  src/pages/post/PostSelectUserTagPage.tsx
  src/recoil/postFormState.ts
Labels: enhancement, refactor

#62 Fix: 채팅 UI 깨짐 수정
  package-lock.json
  package.json
  src/App.tsx
  src/assets/icon/icon-chat-camera.svg
  src/assets/icon/icon-chat-send.svg
  src/components/chat/ChatBottomAndContents.tsx
  src/components/chat/ChatHistoryUserUI.tsx
  src/components/chat/ChatSelectUserUI.tsx
  src/firebase/config.js
  src/pages/chat/ChatHistoryPage.tsx
  src/pages/chat/ChatRoomPage.tsx
  src/pages/chat/ChatSelectUserPage.tsx
Labels: bug, enhancement

#64 Fix: 회원가입 및 Firestore hook 충돌 해결
  src/hooks/useFirestoreCreate.tsx
  src/hooks/useSignUp.ts
Labels: bug, refactor

#67 🛠Feat: 게시물 작성 - 데이터 연동 && Atom 추가 #53 Revert
  src/assets/icon/icon-reupload.svg
  src/components/common/AlertBox.tsx
  src/components/common/FolderList.tsx
  src/components/post/PostFilterPreview.tsx
  src/components/post/PostHeader.tsx
  src/components/post/PostInput.tsx
  src/components/post/PostSearchBar.tsx
  src/components/post/PostSelectedFilter.tsx
  src/components/post/PostSelectedPicture.tsx
  src/hooks/useWindowHeight.tsx
  src/pages/PostTS.tsx
  src/pages/post/PostCreateFolderPage.tsx
  src/pages/post/PostFilterPage.tsx
  src/pages/post/PostInputInfoPage.tsx
  src/pages/post/PostSelectFolderPage.tsx
  src/pages/post/PostSelectHashTagPage.tsx
  src/pages/post/PostSelectUserTagPage.tsx
  src/recoil/postFormState.ts
Labels: enhancement, style, refactor

#69 🛠Feat: 게시글 뷰 - 게시글 및 댓글 기능 구현 #66
  src/components/main/MainComment.tsx
  src/components/main/MainPostItem.tsx
  src/components/main/MainPostMoreMenu.tsx
  src/components/main/MainUserItem.tsx
  src/components/post/PostHeader.tsx
  src/hooks/useFirestoreCreate.tsx
  src/hooks/useFirestoreDelete.tsx
  src/hooks/useFirestoreRead.tsx
  src/hooks/useFirestoreUpdate.tsx
  src/hooks/useImageUpload.tsx
  src/hooks/useLogin.ts
  src/hooks/useModalControl.tsx
  src/pages/main/MainPostViewPage.tsx
  src/pages/post/PostSelectFolderPage.tsx
  src/pages/post/PostSelectUserTagPage.tsx
  src/pages/search/SearchHistoryPage.tsx
  src/recoil/loginToken.ts
  src/utils/getUserInfo.tsx
Labels: enhancement, refactor

#68 🛠Feat: 검색 기능 Firebase 연동
  src/components/search/SearchAccountItem.tsx
  src/components/search/SearchAccountList.tsx
  src/components/search/SearchBar.tsx
  src/components/search/SearchFolderItem.tsx
  src/components/search/SearchFolderList.tsx
  src/components/search/SearchHistoryItem.tsx
  src/components/search/SearchPostItem.tsx
  src/components/search/SearchPostList.tsx
  src/components/search/SearchTagItem.tsx
  src/components/search/SearchTagList.tsx
  src/components/search/SearchTrendingFolderItem.tsx
  src/components/search/SearchTrendingFolderList.tsx
  src/components/search/SearchTrendingTagList.tsx
  src/hooks/useFirestoreRead.tsx
  src/hooks/useFirestoreUpdate.tsx
  src/pages/search/SearchHistoryPage.tsx
  src/pages/search/SearchTrendingFolderPage.tsx
  src/utils/formatNumber.ts
Labels: enhancement, refactor
