Repository Sowith/sowith, pull requests merged in 2023-10, with the labels that each got.

#44 🎨Design: 메인 화면 디자인 구현 #40
  src/App.tsx
  src/assets/icon/icon-bottom_post_section_bar.svg
  src/assets/icon/icon-bottomnav-add_post.svg
  src/assets/icon/icon-bottomnav-home.svg
  src/assets/icon/icon-bottomnav-profile.svg
  src/assets/icon/icon-bottomnav-send_messages.svg
  src/assets/icon/icon-current_location.svg
  src/assets/icon/icon-post_view.svg
  src/components/common/BottomNavBar.tsx
  src/components/search/SearchHistory.tsx
  src/components/search/SearchTrendingFolderList.tsx
  src/components/search/SearchTrendingTagItem.tsx
  src/components/search/SearchTrendingTagList.tsx
  src/pages/Test.tsx
  src/pages/home/HomePage.tsx
  src/pages/search/SearchMainPage.tsx
Labels: enhancement, style

#46 🎨Design: 검색 기록 페이지 피드백 반영 #41
  src/App.tsx
  src/components/search/SearchBar.tsx
  src/pages/profile/ProfileGroupDetailPage.tsx
  src/pages/search/SearchByCategoryPage.tsx
  src/pages/search/SearchHistoryPage.tsx
  src/pages/search/SearchMainPage.tsx
Labels: enhancement, refactor

#48 🎨Design: 검색 메인 페이지 디자인 구현 #39
  src/assets/icon/icon-heart_filled.svg
  src/assets/icon/icon-heart_unfilled.svg
  src/components/search/SearchFolderItem.tsx
  src/components/search/SearchTrendingFolderItem.tsx
Labels: enhancement, style

#51 🎨Design: 게시글 뷰 디자인 구현 #43
  src/App.tsx
  src/assets/icon/icon-bookmark-post-only.svg
  src/assets/icon/icon-like-heart.svg
  src/assets/icon/icon-location-pin.svg
  src/assets/icon/icon-s-report-message.svg
  src/assets/icon/icon-s-trash-delete.svg
  src/assets/icon/icon-share.svg
  src/assets/icon/icon-switch-map.svg
  src/assets/icon/icon-trash-delete.svg
  src/components/common/AlertBox.tsx
  src/components/main/MainComment.tsx
  src/components/main/MainPostItem.tsx
  src/components/main/MainPostMoreMenu.tsx
  src/components/main/MainUserItem.tsx
  src/components/post/PostSelectedFilter.tsx
  src/components/post/PostUserItem.tsx
  src/hooks/useAlertControl.tsx
  src/hooks/useModalControl.tsx
  src/pages/Test.tsx
  src/pages/main/MainPostViewPage.tsx
Labels: enhancement, style

#52 🛠Feat: FireStore 연동 - CRUD 커스텀훅 생성 #50
  src/App.tsx
  src/components/crud/CreateData.tsx
  src/components/crud/DeleteData.tsx
  src/components/crud/ReadData.tsx
  src/components/crud/UpdateData.tsx
  src/firebase/config.js
  src/hooks/useFirestoreCreate.tsx
  src/hooks/useFirestoreDelete.tsx
  src/hooks/useFirestoreRead.tsx
  src/hooks/useFirestoreUpdate.tsx
  src/hooks/useLogin.ts
  src/pages/Test.tsx
  src/recoil/loginToken.ts
Labels: enhancement
